import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import CanvasComponent from "@/components/CanvasComponent";
import { useContext, useEffect, useState } from "react";
import AppContext from "../components/AppContext";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const value = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Predictor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-[#f46b45] to-[#eea849] h-screen flex flex-col justify-evenly">
        <div className=" flex flex-row justify-around items-center">
          <CanvasComponent />
          <button
            className="text-white p-3 rounded-2xl font-semibold text-[15px] bg-black hover:bg-blue-950 "
            onClick={() => {
              value.setImageSrc("");
            }}
          >
            Reset Predicted Image
          </button>
          <div className="bg-white p-6 text-white rounded-[50px] drop-shadow-2xl w-[500px] h-[500px] flex items-center justify-center">
            {value.imageSrc ? (
              // eslint-disable-next-line @next/next/no-img-element
              <Image
              
                className="rounded-[50px]"
                src={value.imageSrc}
                alt="Received Image"
                width={1000}
                height={1000}
              />
            ) : (
              <h1 className="text-gray-600 opacity-50 text-[30px] align-middle text-center">
                Use Predict to Generate
              </h1>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
